// Temp Table Structure

struct TabColumns
{
	char * columnName;
	char * columnType;
	int defaultFlag;
	char * defaultValue;
	int keyFlag;
	int autoGeneratedFlag;
};

struct TableKey
{
	int keyFlag;
	char * columnNames;
};

struct TableQuery
{
	char * tableName;
	int colCount;
	struct TabColumns * tableColumns;
	int keyType; // Specified while columns or separately
};
